services:
  backend:
    build: ./backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=surveydb;Username=postgres;Password=t9LiJBEHFX

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t9LiJBEHFX
    ports:
      - "5432:5432"
