services:
  backend:
    build: ./backend/Survey.API
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=surveydb;Username=postgres;Password=t9LiJBEHFX

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t9LiJBEHFX # TODO JAF set in GitHub secrets
    ports:
      - "5432:5432"
