//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface QuestionnaireDto {
    QuestionnaireId: number;
    QuestionnaireTitle: string;
    InputType: string;
    Range: string;
    SurveyId: number | undefined;
    MultipleChoices: MultipleChoiceDto[];
}

export interface MultipleChoiceDto {
    MultipleChoiceId: number;
    MultipleChoiceName: string;
}

export interface DesignedSurveyDto {
    SurveyId: number | undefined;
    SurveyTitle: string | undefined;
    SurveyDescription: string | undefined;
    StartDate: Date | undefined;
    EndDate: Date | undefined;
    SurveyTypeId: number | undefined;
    PrivateKey: string | undefined;
    UserId: number | undefined;
    Questionnaires: QuestionnaireDto[] | undefined;
}