//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface SurveyStoredAnwsersDto {
    QuestionnaireId: number | undefined;
    QuestionnaireTitle: string | undefined;
    InputType: string | undefined;
    Range: string | undefined;
    SurveyAnswer: string | undefined;
    MultipleChoices: MultipleChoicesDto[] | undefined;
}

export interface MultipleChoicesDto {
    MultipleChoiceId: number | undefined;
    MultipleChoiceName: string | undefined;
}

export interface ExperimenteeAppDto {
    SurveyId: number | undefined;
    SurveyTitle: string | undefined;
    SurveyDescription: string | undefined;
    UserId: number | undefined;
    SurveyStoredAnwsers: SurveyStoredAnwsersDto[] | undefined;
}