//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface ExportQuestionnaire {
    QuestionnaireTitle: string;
    InputType: string;
    Range: string;
    Options: ExportMultipleChoice[];
}

export interface ExportMultipleChoice {
    Option: string;
}

export interface ExportSurvey {
    SurveyTitle: string;
    SurveyDescription: string;
    StartDate: Date;
    EndDate: Date;
    SurveyType: string;
    Questionnaires: ExportQuestionnaire[];
}