//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface JwtSettings {
    Secret: string;
    Issuer: string;
    Audience: string;
    ExpiryMinutes: number;
}