//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface SurveySaveAnswerDto {
    QuestionnaireId: number | undefined;
    QuestionnaireTitle: string | undefined;
    InputType: string | undefined;
    Range: string | undefined;
    SurveyAnswer: string | undefined;
    SurveyId: number | undefined;
    UserId: number | undefined;
}