//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.9.0.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface UserDto {
    UserId: number | undefined;
    UserName: string | undefined;
    UserEmail: string | undefined;
    UserPassword: string | undefined;
    UserTypeId: number | undefined;
}