// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Survey.Infrastructure.Data;

#nullable disable

namespace Survey.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20250523201359_Test123")]
    partial class Test123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Survey.Domain.Entities.DesignedSurvey", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("text");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SurveyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurveyTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SurveyTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SurveyId");

                    b.HasIndex("SurveyTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Survey.Domain.Entities.MultipleChoice", b =>
                {
                    b.Property<int>("MultipleChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MultipleChoiceId"));

                    b.Property<string>("MultipleChoiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("integer");

                    b.HasKey("MultipleChoiceId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("MultipleChoice");
                });

            modelBuilder.Entity("Survey.Domain.Entities.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionnaireId"));

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionnairePos")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionnaireTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SurveyId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyAnswer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("integer");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("SurveyId", "UserId");

                    b.ToTable("SurveyAnswer");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyCompletion", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SurveyCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SurveyCompletionTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SurveyCompletionTypeId1")
                        .HasColumnType("integer");

                    b.HasKey("SurveyId", "UserId");

                    b.HasIndex("SurveyCompletionTypeId");

                    b.HasIndex("SurveyCompletionTypeId1");

                    b.HasIndex("UserId");

                    b.ToTable("SurveyCompletion");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyCompletionType", b =>
                {
                    b.Property<int>("SurveyCompletionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyCompletionTypeId"));

                    b.Property<string>("SurveyCompletionTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SurveyCompletionTypeId");

                    b.ToTable("SurveyCompletionTypes");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyType", b =>
                {
                    b.Property<int>("SurveyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SurveyTypeId"));

                    b.Property<string>("SurveyTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SurveyTypeId");

                    b.ToTable("SurveyTypes");
                });

            modelBuilder.Entity("Survey.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Survey.Domain.Entities.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("Survey.Domain.Entities.DesignedSurvey", b =>
                {
                    b.HasOne("Survey.Domain.Entities.SurveyType", "SurveyType")
                        .WithMany("DesignedSurveys")
                        .HasForeignKey("SurveyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Survey.Domain.Entities.User", "User")
                        .WithMany("Surveys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Survey.Domain.Entities.MultipleChoice", b =>
                {
                    b.HasOne("Survey.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("MultipleChoices")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("Survey.Domain.Entities.Questionnaire", b =>
                {
                    b.HasOne("Survey.Domain.Entities.DesignedSurvey", "Survey")
                        .WithMany("Questionnaires")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("Survey.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("SurveyAnswers")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Survey.Domain.Entities.SurveyCompletion", "SurveyCompletion")
                        .WithMany("SurveyAnswers")
                        .HasForeignKey("SurveyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");

                    b.Navigation("SurveyCompletion");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyCompletion", b =>
                {
                    b.HasOne("Survey.Domain.Entities.SurveyCompletionType", "SurveyCompletionType")
                        .WithMany()
                        .HasForeignKey("SurveyCompletionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Survey.Domain.Entities.SurveyCompletionType", null)
                        .WithMany("SurveyCompletions")
                        .HasForeignKey("SurveyCompletionTypeId1")
                        .HasConstraintName("FK_SurveyCompletion_SurveyCompletionTypes_SurveyCompletionTyp~1");

                    b.HasOne("Survey.Domain.Entities.DesignedSurvey", "Survey")
                        .WithMany("SurveyCompletions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Survey.Domain.Entities.User", "User")
                        .WithMany("SurveyCompletions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");

                    b.Navigation("SurveyCompletionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Survey.Domain.Entities.User", b =>
                {
                    b.HasOne("Survey.Domain.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Survey.Domain.Entities.DesignedSurvey", b =>
                {
                    b.Navigation("Questionnaires");

                    b.Navigation("SurveyCompletions");
                });

            modelBuilder.Entity("Survey.Domain.Entities.Questionnaire", b =>
                {
                    b.Navigation("MultipleChoices");

                    b.Navigation("SurveyAnswers");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyCompletion", b =>
                {
                    b.Navigation("SurveyAnswers");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyCompletionType", b =>
                {
                    b.Navigation("SurveyCompletions");
                });

            modelBuilder.Entity("Survey.Domain.Entities.SurveyType", b =>
                {
                    b.Navigation("DesignedSurveys");
                });

            modelBuilder.Entity("Survey.Domain.Entities.User", b =>
                {
                    b.Navigation("SurveyCompletions");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("Survey.Domain.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
